### ISSUE TITLE
Initial color palette

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/broom#96]
### Resources

https://www.figma.com/file/ytEIsjZoaeRlY4f6IxxEps/Broom?type=design&node-id=539-251&mode=design&t=Nfwd8zWdASND7n5x-11

### Tasks

- [x] Choose initial colors - @whereissally 
- [x] Create initial guidelines on the Design system _(Figma)_ for colors - @whereissally
- [x] Create initial tokens in `@libs/token` for colors palette - @xeho91
- [x] Create documentation on the Storybook - @xeho91
- [x] Provide resources for the documentation about colors palette on the [project's handbook](https://shan-shan.gitbook.io/handbook) - @xeho91
